# -*- coding: utf-8 -*-
"""screentime.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m5-SLj4mi5oef18Jav8QoXKRBo08Z_d8
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd


df = pd.read_csv("Indian_Kids_Screen_Time.csv")

# Check if there are any missing values
print(df.isnull().values.any())

# Or count missing values in each column
print(df.isnull().sum())

df = pd.read_csv("Indian_Kids_Screen_Time.csv")

# Check for duplicate rows
duplicates = df.duplicated()

print(duplicates)

print("First 5 rows:")
print(df.head())

print(df.dtypes)

# information about the dataframe
df.info()

# missing value anywhere in the dataset
print(df.isnull().values.any())
print(df.isnull().sum())

print(df[df.isnull().any(axis=1)])

correlation = df['Age'].corr(df['Avg_Daily_Screen_Time_hr'])

print("Correlation between Age and Avg_Daily_Screen_Time_hr:", correlation)

"""# New Section"""